/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Crowdfunding {
      
    export type CampaignStruct = {creator: AddressLike, goal: BigNumberish, deadline: BigNumberish, totalRaised: BigNumberish, totalReleased: BigNumberish, status: BigNumberish, milestoneCount: BigNumberish, currentMilestone: BigNumberish, goalFinalized: boolean}

    export type CampaignStructOutput = [creator: string, goal: bigint, deadline: bigint, totalRaised: bigint, totalReleased: bigint, status: bigint, milestoneCount: bigint, currentMilestone: bigint, goalFinalized: boolean] & {creator: string, goal: bigint, deadline: bigint, totalRaised: bigint, totalReleased: bigint, status: bigint, milestoneCount: bigint, currentMilestone: bigint, goalFinalized: boolean }
  

    export type MilestoneStruct = {amount: BigNumberish, status: BigNumberish, votingDeadline: BigNumberish, votesFor: BigNumberish, votesAgainst: BigNumberish, released: boolean, proofURI: string}

    export type MilestoneStructOutput = [amount: bigint, status: bigint, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint, released: boolean, proofURI: string] & {amount: bigint, status: bigint, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint, released: boolean, proofURI: string }
  
    }

  export interface CrowdfundingInterface extends Interface {
    getFunction(nameOrSignature: "APPROVAL_THRESHOLD_BPS" | "VOTING_PERIOD" | "campaignContributors" | "campaignCount" | "campaignMilestones" | "campaigns" | "cancelCampaign" | "claimRefund" | "contribute" | "contributions" | "createCampaign" | "finalizeFundingResult" | "finalizeMilestoneVote" | "getCampaign" | "getContribution" | "getContributorCount" | "getMilestone" | "getMilestoneCount" | "hasVoted" | "refundClaimed" | "releaseMilestone" | "submitMilestone" | "voteOnMilestone"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCompleted" | "CampaignCreated" | "CampaignStatusChanged" | "ContributionReceived" | "FundsReleased" | "MilestoneApproved" | "MilestoneRejected" | "MilestoneSubmitted" | "RefundClaimed" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'APPROVAL_THRESHOLD_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'VOTING_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignContributors', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'campaignCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignMilestones', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRefund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [BigNumberish, BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'finalizeFundingResult', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeMilestoneVote', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCampaign', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getContribution', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getContributorCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestoneCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'refundClaimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'releaseMilestone', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitMilestone', values: [BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'voteOnMilestone', values: [BigNumberish, BigNumberish, boolean]): string;

    decodeFunctionResult(functionFragment: 'APPROVAL_THRESHOLD_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VOTING_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignContributors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRefund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeFundingResult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeMilestoneVote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContributorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestoneCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voteOnMilestone', data: BytesLike): Result;
  }

  
    export namespace CampaignCompletedEvent {
      export type InputTuple = [campaignId: BigNumberish];
      export type OutputTuple = [campaignId: bigint];
      export interface OutputObject {campaignId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignCreatedEvent {
      export type InputTuple = [campaignId: BigNumberish, creator: AddressLike, goal: BigNumberish, deadline: BigNumberish, milestoneAmounts: BigNumberish[]];
      export type OutputTuple = [campaignId: bigint, creator: string, goal: bigint, deadline: bigint, milestoneAmounts: bigint[]];
      export interface OutputObject {campaignId: bigint, creator: string, goal: bigint, deadline: bigint, milestoneAmounts: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CampaignStatusChangedEvent {
      export type InputTuple = [campaignId: BigNumberish, status: BigNumberish];
      export type OutputTuple = [campaignId: bigint, status: bigint];
      export interface OutputObject {campaignId: bigint, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContributionReceivedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish, totalRaised: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint, totalRaised: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint, totalRaised: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsReleasedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneId: BigNumberish, creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneId: bigint, creator: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, milestoneId: bigint, creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneId: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneId: bigint];
      export interface OutputObject {campaignId: bigint, milestoneId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneRejectedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneId: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneId: bigint];
      export interface OutputObject {campaignId: bigint, milestoneId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneSubmittedEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneId: BigNumberish, proofURI: string, votingDeadline: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneId: bigint, proofURI: string, votingDeadline: bigint];
      export interface OutputObject {campaignId: bigint, milestoneId: bigint, proofURI: string, votingDeadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RefundClaimedEvent {
      export type InputTuple = [campaignId: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [campaignId: bigint, contributor: string, amount: bigint];
      export interface OutputObject {campaignId: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [campaignId: BigNumberish, milestoneId: BigNumberish, voter: AddressLike, support: boolean, weight: BigNumberish];
      export type OutputTuple = [campaignId: bigint, milestoneId: bigint, voter: string, support: boolean, weight: bigint];
      export interface OutputObject {campaignId: bigint, milestoneId: bigint, voter: string, support: boolean, weight: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Crowdfunding extends BaseContract {
    
    connect(runner?: ContractRunner | null): Crowdfunding;
    waitForDeployment(): Promise<this>;

    interface: CrowdfundingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    APPROVAL_THRESHOLD_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VOTING_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaignContributors: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    campaignCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaignMilestones: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, boolean, string] & {amount: bigint, status: bigint, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint, released: boolean, proofURI: string }],
      'view'
    >
    

    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {creator: string, goal: bigint, deadline: bigint, totalRaised: bigint, totalReleased: bigint, status: bigint, milestoneCount: bigint, currentMilestone: bigint, goalFinalized: boolean }],
      'view'
    >
    

    
    cancelCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimRefund: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    contribute: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [goal: BigNumberish, deadline: BigNumberish, milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    finalizeFundingResult: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeMilestoneVote: TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCampaign: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput],
      'view'
    >
    

    
    getContribution: TypedContractMethod<
      [campaignId: BigNumberish, contributor: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getContributorCount: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getMilestone: TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [Crowdfunding.MilestoneStructOutput],
      'view'
    >
    

    
    getMilestoneCount: TypedContractMethod<
      [campaignId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    refundClaimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    releaseMilestone: TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitMilestone: TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, proofURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    voteOnMilestone: TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'APPROVAL_THRESHOLD_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VOTING_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaignContributors'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'campaignCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaignMilestones'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, boolean, string] & {amount: bigint, status: bigint, votingDeadline: bigint, votesFor: bigint, votesAgainst: bigint, released: boolean, proofURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {creator: string, goal: bigint, deadline: bigint, totalRaised: bigint, totalReleased: bigint, status: bigint, milestoneCount: bigint, currentMilestone: bigint, goalFinalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'cancelCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRefund'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [goal: BigNumberish, deadline: BigNumberish, milestoneAmounts: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeFundingResult'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeMilestoneVote'): TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCampaign'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [Crowdfunding.CampaignStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getContribution'): TypedContractMethod<
      [campaignId: BigNumberish, contributor: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getContributorCount'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestone'): TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [Crowdfunding.MilestoneStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestoneCount'): TypedContractMethod<
      [campaignId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, arg2: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refundClaimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'releaseMilestone'): TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitMilestone'): TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, proofURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voteOnMilestone'): TypedContractMethod<
      [campaignId: BigNumberish, milestoneId: BigNumberish, support: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignCompleted'): TypedContractEvent<CampaignCompletedEvent.InputTuple, CampaignCompletedEvent.OutputTuple, CampaignCompletedEvent.OutputObject>;
getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'CampaignStatusChanged'): TypedContractEvent<CampaignStatusChangedEvent.InputTuple, CampaignStatusChangedEvent.OutputTuple, CampaignStatusChangedEvent.OutputObject>;
getEvent(key: 'ContributionReceived'): TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
getEvent(key: 'FundsReleased'): TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'MilestoneRejected'): TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
getEvent(key: 'MilestoneSubmitted'): TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
getEvent(key: 'RefundClaimed'): TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'CampaignCompleted(uint256)': TypedContractEvent<CampaignCompletedEvent.InputTuple, CampaignCompletedEvent.OutputTuple, CampaignCompletedEvent.OutputObject>;
      CampaignCompleted: TypedContractEvent<CampaignCompletedEvent.InputTuple, CampaignCompletedEvent.OutputTuple, CampaignCompletedEvent.OutputObject>;
    

      'CampaignCreated(uint256,address,uint256,uint256,uint256[])': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'CampaignStatusChanged(uint256,uint8)': TypedContractEvent<CampaignStatusChangedEvent.InputTuple, CampaignStatusChangedEvent.OutputTuple, CampaignStatusChangedEvent.OutputObject>;
      CampaignStatusChanged: TypedContractEvent<CampaignStatusChangedEvent.InputTuple, CampaignStatusChangedEvent.OutputTuple, CampaignStatusChangedEvent.OutputObject>;
    

      'ContributionReceived(uint256,address,uint256,uint256)': TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
      ContributionReceived: TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
    

      'FundsReleased(uint256,uint256,address,uint256)': TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
      FundsReleased: TypedContractEvent<FundsReleasedEvent.InputTuple, FundsReleasedEvent.OutputTuple, FundsReleasedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'MilestoneRejected(uint256,uint256)': TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
      MilestoneRejected: TypedContractEvent<MilestoneRejectedEvent.InputTuple, MilestoneRejectedEvent.OutputTuple, MilestoneRejectedEvent.OutputObject>;
    

      'MilestoneSubmitted(uint256,uint256,string,uint256)': TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
      MilestoneSubmitted: TypedContractEvent<MilestoneSubmittedEvent.InputTuple, MilestoneSubmittedEvent.OutputTuple, MilestoneSubmittedEvent.OutputObject>;
    

      'RefundClaimed(uint256,address,uint256)': TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
      RefundClaimed: TypedContractEvent<RefundClaimedEvent.InputTuple, RefundClaimedEvent.OutputTuple, RefundClaimedEvent.OutputObject>;
    

      'VoteCast(uint256,uint256,address,bool,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }